from __future__ import annotations
from typing import Any, Literal, Optional

CardCompany = Literal["KOREA_DEVELOPMENT_BANK", "KFCC", "SHINHYUP", "EPOST", "SAVINGS_BANK_KOREA", "KAKAO_BANK", "K_BANK", "TOSS_BANK", "WOORI_CARD", "BC_CARD", "GWANGJU_CARD", "SAMSUNG_CARD", "SHINHAN_CARD", "HYUNDAI_CARD", "LOTTE_CARD", "SUHYUP_CARD", "CITI_CARD", "NH_CARD", "JEONBUK_CARD", "JEJU_CARD", "HANA_CARD", "KOOKMIN_CARD", "UNIDENTIFIED_GLOBAL_CARD", "CHAI_CARD", "AMEX_CARD", "MIR_CARD", "UNION_CARD", "JCB_CARD", "VISA_CARD", "MASTER_CARD", "DINERS_CARD", "DISCOVER_CARD", "IBK", "NH_BANK", "DAEGU_CARD", "BUSAN_CARD", "SC_BANK", "KYONGNAM_CARD", "WOORI_BANK", "CHINA_BANK", "NFCF", "KB_SECURITIES", "YUANTA_SECURITIES", "NH_SECURITIES", "DB_SECURITIES", "SK_SECURITIES", "EUGENE_SECURITIES", "KYOBO_SECURITIES", "MIRAE_ASSET_SECURITIES", "KOREA_SECURITIES", "HANHWA_SECURITIES", "SSG", "KONA_I", "CHAI", "TOSS_CARD", "PAYCO", "GMONEY_TRANS", "FINT", "KG_MOBILIANS", "HANPASS", "FINSHOT", "BIZPLAY", "NICE", "DANAL", "SECTA", "GME", "LORD_SYSTEM", "NAVERPAY", "KAKAOPAY", "KDBC", "TEEN_CASH", "EGG_MONEY", "ON_CASH", "GALAXIA_MONEY_TREE", "FIRFIN"]
"""카드사
"""


def _serialize_card_company(obj: CardCompany) -> Any:
    return obj


def _deserialize_card_company(obj: Any) -> CardCompany:
    if obj not in ["KOREA_DEVELOPMENT_BANK", "KFCC", "SHINHYUP", "EPOST", "SAVINGS_BANK_KOREA", "KAKAO_BANK", "K_BANK", "TOSS_BANK", "WOORI_CARD", "BC_CARD", "GWANGJU_CARD", "SAMSUNG_CARD", "SHINHAN_CARD", "HYUNDAI_CARD", "LOTTE_CARD", "SUHYUP_CARD", "CITI_CARD", "NH_CARD", "JEONBUK_CARD", "JEJU_CARD", "HANA_CARD", "KOOKMIN_CARD", "UNIDENTIFIED_GLOBAL_CARD", "CHAI_CARD", "AMEX_CARD", "MIR_CARD", "UNION_CARD", "JCB_CARD", "VISA_CARD", "MASTER_CARD", "DINERS_CARD", "DISCOVER_CARD", "IBK", "NH_BANK", "DAEGU_CARD", "BUSAN_CARD", "SC_BANK", "KYONGNAM_CARD", "WOORI_BANK", "CHINA_BANK", "NFCF", "KB_SECURITIES", "YUANTA_SECURITIES", "NH_SECURITIES", "DB_SECURITIES", "SK_SECURITIES", "EUGENE_SECURITIES", "KYOBO_SECURITIES", "MIRAE_ASSET_SECURITIES", "KOREA_SECURITIES", "HANHWA_SECURITIES", "SSG", "KONA_I", "CHAI", "TOSS_CARD", "PAYCO", "GMONEY_TRANS", "FINT", "KG_MOBILIANS", "HANPASS", "FINSHOT", "BIZPLAY", "NICE", "DANAL", "SECTA", "GME", "LORD_SYSTEM", "NAVERPAY", "KAKAOPAY", "KDBC", "TEEN_CASH", "EGG_MONEY", "ON_CASH", "GALAXIA_MONEY_TREE", "FIRFIN"]:
        raise ValueError(f"{repr(obj)} is not CardCompany")
    return obj
