name: JavaScript SDK

on:
  push:
    paths:
      - "javascript/**"
      - ".github/workflows/javascript.yml"
      - "codegen/openapi.json"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  docs:
    name: Publish API reference
    needs: [check, test]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./javascript
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          package_json_file: ./javascript/package.json
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ./javascript/pnpm-lock.yaml
      - name: Install Dependencies
        run: pnpm install
      - name: Run typedoc
        run: pnpm typedoc
      - name: Deploy on GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./javascript/docs
          destination_dir: js
  check:
    name: Check
    if: ${{ startsWith(github.ref, 'refs/heads') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./javascript
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          package_json_file: ./javascript/package.json
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ./javascript/pnpm-lock.yaml
      - name: Install Dependencies
        run: pnpm install
      - name: Run biome check
        run: pnpm biome check
  test:
    name: Test
    if: ${{ startsWith(github.ref, 'refs/heads') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./javascript
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          package_json_file: ./javascript/package.json
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ./javascript/pnpm-lock.yaml
      - name: Install Dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test --silent
        env:
          PORTONE_API_SECRET: ${{ secrets.PORTONE_API_SECRET }}
  release:
    name: Release
    needs: [check, test]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment:
      name: NPM
      url: https://www.npmjs.com/package/@portone/server-sdk
    defaults:
      run:
        working-directory: ./javascript
    permissions:
      pull-requests: write
      contents: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          package_json_file: ./javascript/package.json

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ./javascript/pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          cwd: ./javascript
          publish: pnpm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send a Slack notification if a publish happens
        if: ${{ steps.changesets.outputs.hasChangesets == 'false' }}
        run: |
          export VERSION=$(jq -r '.version' package.json)
          curl -X POST -H 'Content-type: application/json'\
            --data '{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"npm과 jsr에 `@portone/server-sdk` 버전 *v'"$VERSION"'* 가 배포되었습니다 :rocket:"}},{"type":"actions","elements":[{"type":"button","text":{"type":"plain_text","text":"npm 페이지 보기"},"value":"show_npm_page","url":"https://www.npmjs.com/package/@portone/server-sdk/v/'"$VERSION"'","action_id":"show_npm_page"},{"type":"button","text":{"type":"plain_text","text":"jsr 페이지 보기"},"value":"show_jsr_page","url":"https://jsr.io/@portone/server-sdk@'"$VERSION"'","action_id":"show_jsr_page"},{"type":"button","text":{"type":"plain_text","text":"체인지로그 보기"},"value":"show_changelog","url":"https://github.com/portone-io/server-sdk/blob/main/javascript/CHANGELOG.md","action_id":"show_changelog"}]}]}'\
            ${{ secrets.SLACK_WEBHOOK_URL }}
